ONGDB-244 - Windows package failing to startup with invalid start command

diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/ongdb b/packaging/standalone/src/main/distribution/shell-scripts/bin/ongdb
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/ongdb
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/ongdb
@@ -17,8 +17,8 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# Copyright (c) 2002-2018 "Neo Technology,"
-# Network Engine for Objects in Lund AB [http://neotechnology.com]
+# Copyright (c) 2002-2019 "Neo4j,"
+# Neo4j Sweden AB [http://neo4j.com]
 #
 # This file is part of Neo4j.
 #
@@ -35,6 +35,7 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
+
 # Callers may provide the following environment variables to customize this script:
 #  * JAVA_HOME
 #  * JAVA_CMD
@@ -42,6 +43,9 @@
 #  * ONGDB_CONF
 #  * ONGDB_START_WAIT
 
+#############################################################
+#      File content is generated based on .m4 template      #
+#############################################################
 
 set -o errexit -o nounset -o pipefail
 [[ "${TRACE:-}" ]] && set -o xtrace
@@ -67,9 +71,9 @@ setup_environment() {
 }
 
 setup_heap() {
-  JAVA_MEMORY_OPTS=()
   if [[ -n "${HEAP_SIZE:-}" ]]; then
-    JAVA_MEMORY_OPTS+=("-Xmx${HEAP_SIZE}")
+    JAVA_MEMORY_OPTS_XMS="-Xms${HEAP_SIZE}"
+    JAVA_MEMORY_OPTS_XMX="-Xmx${HEAP_SIZE}"
   fi
 }
 
@@ -95,23 +99,69 @@ detect_os() {
   fi
 }
 
+setup_memory_opts() {
+  # In some cases the heap size may have already been set before we get here, from e.g. HEAP_SIZE env.variable, if so then skip
+  if [[ -n "${dbms_memory_heap_initial_size:-}" && -z "${JAVA_MEMORY_OPTS_XMS-}" ]]; then
+    local mem="${dbms_memory_heap_initial_size}"
+    if ! [[ ${mem} =~ .*[gGmMkK] ]]; then
+      mem="${mem}m"
+      cat >&2 <<EOF
+WARNING: dbms.memory.heap.initial_size will require a unit suffix in a
+         future version of ONgDB. Please add a unit suffix to your
+         configuration. Example:
+
+         dbms.memory.heap.initial_size=512m
+                                          ^
+EOF
+    fi
+    JAVA_MEMORY_OPTS_XMS="-Xms${mem}"
+  fi
+  # In some cases the heap size may have already been set before we get here, from e.g. HEAP_SIZE env.variable, if so then skip
+  if [[ -n "${dbms_memory_heap_max_size:-}" && -z "${JAVA_MEMORY_OPTS_XMX-}" ]]; then
+    local mem="${dbms_memory_heap_max_size}"
+    if ! [[ ${mem} =~ .*[gGmMkK] ]]; then
+      mem="${mem}m"
+      cat >&2 <<EOF
+WARNING: dbms.memory.heap.max_size will require a unit suffix in a
+         future version of ONgDB. Please add a unit suffix to your
+         configuration. Example:
+
+         dbms.memory.heap.max_size=512m
+                                      ^
+EOF
+    fi
+    JAVA_MEMORY_OPTS_XMX="-Xmx${mem}"
+  fi
+}
+
 check_java() {
   _find_java_cmd
+  setup_memory_opts
 
-  version_command=("${JAVA_CMD}" "-version")
-  [[ -n "${JAVA_MEMORY_OPTS:-}" ]] && version_command+=("${JAVA_MEMORY_OPTS[@]}")
+  version_command=("${JAVA_CMD}" "-version" ${JAVA_MEMORY_OPTS_XMS-} ${JAVA_MEMORY_OPTS_XMX-})
 
   JAVA_VERSION=$("${version_command[@]}" 2>&1 | awk -F '"' '/version/ {print $2}')
-  if [[ "${JAVA_VERSION}" < "1.8" ]]; then
-    echo "ERROR! ONgDB cannot be started using java version ${JAVA_VERSION}. "
-    _show_java_help
-    exit 1
+  if [[ $JAVA_VERSION = "1."* ]]; then
+    if [[ "${JAVA_VERSION}" < "1.8" ]]; then
+      echo "ERROR! ONgDB cannot be started using java version ${JAVA_VERSION}. "
+      _show_java_help
+      exit 1
+    fi
+    if ! ("${version_command[@]}" 2>&1 | egrep -q "(Java HotSpot\\(TM\\)|OpenJDK|IBM) (64-Bit Server|Server|Client|J9) VM"); then
+      unsupported_runtime_warning
+    fi
+  elif [[ $JAVA_VERSION = "11"* ]]; then
+    if ! ("${version_command[@]}" 2>&1 | egrep -q "(Java HotSpot\\(TM\\)|OpenJDK|IBM) (64-Bit Server|Server|Client|J9) VM"); then
+       unsupported_runtime_warning
+    fi
+  else
+      unsupported_runtime_warning
   fi
+}
 
-  if ! ("${version_command[@]}" 2>&1 | egrep -q "(Java HotSpot\\(TM\\)|OpenJDK|IBM) (64-Bit Server|Server|Client|J9) VM"); then
+unsupported_runtime_warning() {
     echo "WARNING! You are using an unsupported Java runtime. "
     _show_java_help
-  fi
 }
 
 # Resolve a path relative to $ONGDB_HOME.  Don't resolve if
@@ -136,7 +186,7 @@ call_main_class() {
 
   export ONGDB_HOME ONGDB_CONF
 
-  exec "${JAVA_CMD}" ${JAVA_OPTS:-} ${JAVA_MEMORY_OPTS[@]:-} \
+  exec "${JAVA_CMD}" ${JAVA_OPTS:-} ${JAVA_MEMORY_OPTS_XMS-} ${JAVA_MEMORY_OPTS_XMX-} \
     -classpath "${CLASSPATH}" \
     ${EXTRA_JVM_ARGUMENTS:-} \
     $class_name "$@"
@@ -182,7 +232,7 @@ _find_java_home() {
 
 _show_java_help() {
   echo "* Please use Oracle(R) Java(TM) 8, OpenJDK(TM) or IBM J9 to run ONgDB."
-  echo "* Please see https://graphfoundation.org/docs/ for ONgDB installation instructions."
+  echo "* Please see https://graphfoundation.org/ongdb/docs/ for ONgDB installation instructions."
 }
 
 _setup_calculated_paths() {
@@ -205,10 +255,15 @@ _read_config() {
       if [[ "${key}" =~ ^(.*)_([0-9]+)$ ]]; then
         key="${BASH_REMATCH[1]}"
       fi
-      if [[ "${!key:-}" ]]; then
-        export ${key}="${!key} ${value}"
+      # Ignore keys that start with a number because export ${key}= will fail - it is not valid for a bash env var to start with a digit
+      if [[ ! "${key}" =~ ^[0-9]+.*$ ]]; then
+        if [[ "${!key:-}" ]]; then
+          export ${key}="${!key} ${value}"
+        else
+          export ${key}="${value}"
+        fi
       else
-        export ${key}="${value}"
+        echo >&2 "WARNING: Ignoring key ${key}, environment variables cannot start with a number."
       fi
     fi
   }
@@ -223,7 +278,7 @@ EOF
   for file in "ongdb-wrapper.conf" "ongdb.conf"; do
     path="${ONGDB_CONF}/${file}"
     if [ -e "${path}" ]; then
-      while read line; do
+      while read line || [[ -n "$line" ]]; do
         parse_line "${line}"
       done <"${path}"
     fi
@@ -344,50 +399,31 @@ check_limits() {
 }
 
 setup_java_opts() {
-  JAVA_OPTS=("-server")
-
-  if [[ -n "${dbms_memory_heap_initial_size:-}" ]]; then
-    local mem="${dbms_memory_heap_initial_size}"
-    if ! [[ ${mem} =~ .*[gGmMkK] ]]; then
-      mem="${mem}m"
-      cat >&2 <<EOF
-WARNING: dbms.memory.heap.initial_size will require a unit suffix in a
-         future version of ONgDB. Please add a unit suffix to your
-         configuration. Example:
-
-         dbms.memory.heap.initial_size=512m
-                                          ^
-EOF
-    fi
-    JAVA_MEMORY_OPTS+=("-Xms${mem}")
-  fi
-  if [[ -n "${dbms_memory_heap_max_size:-}" ]]; then
-    local mem="${dbms_memory_heap_max_size}"
-    if ! [[ ${mem} =~ .*[gGmMkK] ]]; then
-      mem="${mem}m"
-      cat >&2 <<EOF
-WARNING: dbms.memory.heap.max_size will require a unit suffix in a
-         future version of ONgDB. Please add a unit suffix to your
-         configuration. Example:
-
-         dbms.memory.heap.max_size=512m
-                                      ^
-EOF
-    fi
-    JAVA_MEMORY_OPTS+=("-Xmx${mem}")
-  fi
-  [[ -n "${JAVA_MEMORY_OPTS:-}" ]] && JAVA_OPTS+=("${JAVA_MEMORY_OPTS[@]}")
+  JAVA_OPTS=("-server" ${JAVA_MEMORY_OPTS_XMS-} ${JAVA_MEMORY_OPTS_XMX-})
 
   if [[ "${dbms_logs_gc_enabled:-}" = "true" ]]; then
-    JAVA_OPTS+=("-Xloggc:${ONGDB_LOGS}/gc.log" \
-                "-XX:+UseGCLogFileRotation" \
-                "-XX:NumberOfGCLogFiles=${dbms_logs_gc_rotation_keep_number:-5}" \
-                "-XX:GCLogFileSize=${dbms_logs_gc_rotation_size:-20m}")
-    if [[ -n "${dbms_logs_gc_options:-}" ]]; then
-      JAVA_OPTS+=(${dbms_logs_gc_options}) # unquoted to split on spaces
+    if [[ "${JAVA_VERSION}" = "1.8"* ]]; then
+      # JAVA 8 GC logging setup
+      JAVA_OPTS+=("-Xloggc:${ONGDB_LOGS}/gc.log" \
+                  "-XX:+UseGCLogFileRotation" \
+                  "-XX:NumberOfGCLogFiles=${dbms_logs_gc_rotation_keep_number:-5}" \
+                  "-XX:GCLogFileSize=${dbms_logs_gc_rotation_size:-20m}")
+      if [[ -n "${dbms_logs_gc_options:-}" ]]; then
+        JAVA_OPTS+=(${dbms_logs_gc_options}) # unquoted to split on spaces
+      else
+        JAVA_OPTS+=("-XX:+PrintGCDetails" "-XX:+PrintGCDateStamps" "-XX:+PrintGCApplicationStoppedTime" \
+                    "-XX:+PrintPromotionFailure" "-XX:+PrintTenuringDistribution")
+      fi
     else
-      JAVA_OPTS+=("-XX:+PrintGCDetails" "-XX:+PrintGCDateStamps" "-XX:+PrintGCApplicationStoppedTime" \
-                  "-XX:+PrintPromotionFailure" "-XX:+PrintTenuringDistribution")
+      # JAVA 9 and newer GC logging setup
+      local gc_options
+      if [[ -n "${dbms_logs_gc_options:-}" ]]; then
+        gc_options="${dbms_logs_gc_options}"
+      else
+        gc_options="-Xlog:gc*,safepoint,age*=trace"
+      fi
+      gc_options+=":file=${ONGDB_LOGS}/gc.log::filecount=${dbms_logs_gc_rotation_keep_number:-5},filesize=${dbms_logs_gc_rotation_size:-20m}"
+      JAVA_OPTS+=(${gc_options})
     fi
   fi
 
@@ -423,6 +459,10 @@ do_start() {
   if [[ "${ONGDB_PID:-}" ]] ; then
     echo "ONgDB is already running (pid ${ONGDB_PID})."
     exit 0
+  fi
+  # check dir for pidfile exists
+  if [[ ! -d $(dirname "${ONGDB_PIDFILE}") ]]; then
+    mkdir -p $(dirname "${ONGDB_PIDFILE}")
   fi
 
   echo "Starting ONgDB."
@@ -461,7 +501,7 @@ do_stop() {
   check_status
 
   if [[ ! "${ONGDB_PID:-}" ]] ; then
-    echo "ONgDB not running"
+    echo "ONgDB is not running"
     [ -e "${ONGDB_PIDFILE}" ] && rm "${ONGDB_PIDFILE}"
     return 0
   else
@@ -509,34 +549,40 @@ do_version() {
   exec "${command_line[@]}"
 }
 
+setup_java () {
+  check_java
+  setup_java_opts
+  setup_arbiter_options
+}
+
 main() {
   setup_environment
   CONSOLE_LOG="${ONGDB_LOGS}/ongdb.log"
   ONGDB_PIDFILE="${ONGDB_RUN}/ongdb.pid"
   readonly CONSOLE_LOG ONGDB_PIDFILE
 
-  setup_java_opts
-  check_java
-  setup_arbiter_options
-
   case "${1:-}" in
     console)
+      setup_java
       print_active_database
       print_configurable_paths
       do_console
       ;;
 
     start)
+      setup_java
       print_active_database
       print_configurable_paths
       do_start
       ;;
 
     stop)
+      setup_arbiter_options
       do_stop
       ;;
 
     restart)
+      setup_java
       do_stop
       do_start
       ;;
@@ -546,6 +592,7 @@ main() {
       ;;
 
     --version|version)
+      setup_java
       do_version
       ;;
 
diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/ongdb-import b/packaging/standalone/src/main/distribution/shell-scripts/bin/ongdb-import
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/ongdb-import
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/ongdb-import
@@ -17,6 +17,24 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+# Copyright (c) 2002-2018 "Neo4j,"
+# Neo4j Sweden AB [http://neo4j.com]
+#
+# This file is part of Neo4j.
+#
+# Neo4j is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
 
 set -o errexit -o nounset -o pipefail
 [[ "${TRACE:-}" ]] && set -o xtrace
@@ -42,9 +60,9 @@ setup_environment() {
 }
 
 setup_heap() {
-  JAVA_MEMORY_OPTS=()
   if [[ -n "${HEAP_SIZE:-}" ]]; then
-    JAVA_MEMORY_OPTS+=("-Xmx${HEAP_SIZE}")
+    JAVA_MEMORY_OPTS_XMS="-Xms${HEAP_SIZE}"
+    JAVA_MEMORY_OPTS_XMX="-Xmx${HEAP_SIZE}"
   fi
 }
 
@@ -70,23 +88,69 @@ detect_os() {
   fi
 }
 
+setup_memory_opts() {
+  # In some cases the heap size may have already been set before we get here, from e.g. HEAP_SIZE env.variable, if so then skip
+  if [[ -n "${dbms_memory_heap_initial_size:-}" && -z "${JAVA_MEMORY_OPTS_XMS-}" ]]; then
+    local mem="${dbms_memory_heap_initial_size}"
+    if ! [[ ${mem} =~ .*[gGmMkK] ]]; then
+      mem="${mem}m"
+      cat >&2 <<EOF
+WARNING: dbms.memory.heap.initial_size will require a unit suffix in a
+         future version of ONgDB. Please add a unit suffix to your
+         configuration. Example:
+
+         dbms.memory.heap.initial_size=512m
+                                          ^
+EOF
+    fi
+    JAVA_MEMORY_OPTS_XMS="-Xms${mem}"
+  fi
+  # In some cases the heap size may have already been set before we get here, from e.g. HEAP_SIZE env.variable, if so then skip
+  if [[ -n "${dbms_memory_heap_max_size:-}" && -z "${JAVA_MEMORY_OPTS_XMX-}" ]]; then
+    local mem="${dbms_memory_heap_max_size}"
+    if ! [[ ${mem} =~ .*[gGmMkK] ]]; then
+      mem="${mem}m"
+      cat >&2 <<EOF
+WARNING: dbms.memory.heap.max_size will require a unit suffix in a
+         future version of ONgDB. Please add a unit suffix to your
+         configuration. Example:
+
+         dbms.memory.heap.max_size=512m
+                                      ^
+EOF
+    fi
+    JAVA_MEMORY_OPTS_XMX="-Xmx${mem}"
+  fi
+}
+
 check_java() {
   _find_java_cmd
+  setup_memory_opts
 
-  version_command=("${JAVA_CMD}" "-version")
-  [[ -n "${JAVA_MEMORY_OPTS:-}" ]] && version_command+=("${JAVA_MEMORY_OPTS[@]}")
+  version_command=("${JAVA_CMD}" "-version" ${JAVA_MEMORY_OPTS_XMS-} ${JAVA_MEMORY_OPTS_XMX-})
 
   JAVA_VERSION=$("${version_command[@]}" 2>&1 | awk -F '"' '/version/ {print $2}')
-  if [[ "${JAVA_VERSION}" < "1.8" ]]; then
-    echo "ERROR! ONgDB cannot be started using java version ${JAVA_VERSION}. "
-    _show_java_help
-    exit 1
+  if [[ $JAVA_VERSION = "1."* ]]; then
+    if [[ "${JAVA_VERSION}" < "1.8" ]]; then
+      echo "ERROR! ONgDB cannot be started using java version ${JAVA_VERSION}. "
+      _show_java_help
+      exit 1
+    fi
+    if ! ("${version_command[@]}" 2>&1 | egrep -q "(Java HotSpot\\(TM\\)|OpenJDK|IBM) (64-Bit Server|Server|Client|J9) VM"); then
+      unsupported_runtime_warning
+    fi
+  elif [[ $JAVA_VERSION = "11"* ]]; then
+    if ! ("${version_command[@]}" 2>&1 | egrep -q "(Java HotSpot\\(TM\\)|OpenJDK|IBM) (64-Bit Server|Server|Client|J9) VM"); then
+       unsupported_runtime_warning
+    fi
+  else
+      unsupported_runtime_warning
   fi
+}
 
-  if ! ("${version_command[@]}" 2>&1 | egrep -q "(Java HotSpot\\(TM\\)|OpenJDK|IBM) (64-Bit Server|Server|Client|J9) VM"); then
+unsupported_runtime_warning() {
     echo "WARNING! You are using an unsupported Java runtime. "
     _show_java_help
-  fi
 }
 
 # Resolve a path relative to $ONGDB_HOME.  Don't resolve if
@@ -111,7 +175,7 @@ call_main_class() {
 
   export ONGDB_HOME ONGDB_CONF
 
-  exec "${JAVA_CMD}" ${JAVA_OPTS:-} ${JAVA_MEMORY_OPTS[@]:-} \
+  exec "${JAVA_CMD}" ${JAVA_OPTS:--XX:+UseParallelGC} ${JAVA_MEMORY_OPTS_XMS-} ${JAVA_MEMORY_OPTS_XMX-} \
     -classpath "${CLASSPATH}" \
     ${EXTRA_JVM_ARGUMENTS:-} \
     $class_name "$@"
@@ -157,7 +221,7 @@ _find_java_home() {
 
 _show_java_help() {
   echo "* Please use Oracle(R) Java(TM) 8, OpenJDK(TM) or IBM J9 to run ONgDB."
-  echo "* Please see https://graphfoundation.org/docs/ for ONgDB installation instructions."
+  echo "* Please see https://graphfoundation.org/ongdb/docs/ for ONgDB installation instructions."
 }
 
 _setup_calculated_paths() {
@@ -180,10 +244,15 @@ _read_config() {
       if [[ "${key}" =~ ^(.*)_([0-9]+)$ ]]; then
         key="${BASH_REMATCH[1]}"
       fi
-      if [[ "${!key:-}" ]]; then
-        export ${key}="${!key} ${value}"
+      # Ignore keys that start with a number because export ${key}= will fail - it is not valid for a bash env var to start with a digit
+      if [[ ! "${key}" =~ ^[0-9]+.*$ ]]; then
+        if [[ "${!key:-}" ]]; then
+          export ${key}="${!key} ${value}"
+        else
+          export ${key}="${value}"
+        fi
       else
-        export ${key}="${value}"
+        echo >&2 "WARNING: Ignoring key ${key}, environment variables cannot start with a number."
       fi
     fi
   }
@@ -198,7 +267,7 @@ EOF
   for file in "ongdb-wrapper.conf" "ongdb.conf"; do
     path="${ONGDB_CONF}/${file}"
     if [ -e "${path}" ]; then
-      while read line; do
+      while read line || [[ -n "$line" ]]; do
         parse_line "${line}"
       done <"${path}"
     fi
